### ISSUE TITLE
BH 1.84.0 CRAN Release Planning

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/bh#100]
Boost 1.84.0 was released last week, and a package 1.84.0 has been prepared (#98, #99). It can be installed from [the ghrr drat](https://ghrr.github.io/drat/) or from [r-universe](https://eddelbuettel.r-universe.dev/BH)

Reverse dependency checks revealed issues with five packages:
- [ ] [FeatureHashing](https://github.com/wush978/FeatureHashing) has had a deprecation warning for some time, as detailed in #84 I failed to update this in 1.81.0 but have added Boost `timer` to 1.84.0, this should be relatively simple once 1.84.0 is on CRAN and can be tested now
- [x] [ldt](https://github.com/rmojab63/LDT) has a new error in tests; I validated this on another machine; no PR yet (new version 0.5.2 on CRAN 2023-12-21)
- [x] [LOMAR](https://git.embl.de/heriche/lomar) needs a change to use of now deprecated `bind` (new version 0.4.0 on CRAN 2023-12-20)
- [ ] [sgd](https://github.com/airoldilab/sgd) also need to switch to `timer.hpp` (or `progress_display.hpp`); as described above this needs 1.84.0 released as it now contains the updated `timer` library 
- [ ] [TDA](https://github.com/compTAG/r-tda) has some fairly complicated RcppEigen and BH interactions as in prior releases

A release of BH to CRAN is planned for early January approximately one week after CRAN reopens and roughly in four weeks from now.

**Comment by eddelbuettel** [comment]
BH 1.84.0-0 is now at CRAN so FeatureHashing and sgd can now update to the new, now preferred, progress header.  I hope TDA finds time to adapt to 1.84.0 too.

**Comment by ptoulis** [comment]
Thanks!
