### ISSUE TITLE
failure to extract the package BH during a download as a dependency to dplyr package

### ISSUE THREAD

**Issue by rizwanahmad** [eddelbuettel/bh#13]
package failed to extract while trying to download as a dependency to dplyr package on R gui for windows ( 32 bit), R 3.2.0.
following is the error message
 utils:::menuInstallPkgs()
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/BH_1.55.0-3.zip'
Content type 'application/zip' length 12472065 bytes (11.9 MB)
downloaded 173 KB

Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 177890 != reported length 12472065
2: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
3: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'BH/DESCRIPTION', probable reason 'No such file or directory'

**Comment by eddelbuettel** [comment]
Try a different mirror.  The package gets installed all the time by autobuilders and some of us.  This is guaranteed to be a local issue.

**Comment by eddelbuettel** [comment]
This issue was moved to eddelbuettel/bh#13
