### ISSUE TITLE
Add boost.compute headers?

### ISSUE THREAD

**Issue by cdeterman** [eddelbuettel/bh#16]
Would it be possible to add the boost.compute headers to the BH package?  These headers would be very helpful for GPU development and seems only right that they should be part of the BH package?  Although I am sure you could find them, the github page is https://github.com/boostorg/compute

I'm not sure what you policy is exactly on adding additional boost components but it couldn't hurt to ask.

**Comment by eddelbuettel** [comment]
You are doing the right thing: asking ;-)  I think we recommend just that (ask; issue ticket) in the README.md file.

But we do use [boost.org](http://www.boost.org) *releases* and I do not see 1.58 containing Boost.Compute.  The link you provide points to the unreleased GH repos for Boost 2 and beyond.

And [this page](http://boostorg.github.io/compute/boost_compute/getting_started.html#boost_compute.getting_started.downloading) confirms it.  So sorry -- outside of the BH spec.

**Comment by eddelbuettel** [comment]
This issue was moved to eddelbuettel/bh#16

**Comment by eddelbuettel** [comment]
Yep, agreed!

**Comment by eddelbuettel** [comment]
This is now in master and should be on CRAN "soon".
