### ISSUE TITLE
Hi, I got a problem using cpp_bin_float

### ISSUE THREAD

**Issue by zh9118** [eddelbuettel/bh#17]
Hi,
When I used cpp_bin_float, I got a problem and couldn't compile the code. Could anyone please help me about this? Thanks a lot.

![image](https://cloud.githubusercontent.com/assets/13088022/8396990/817dc91e-1d79-11e5-8d44-c09de30b6a22.png)

And the examples I tried was from boost::multiprecision::cpp_bin_float website. :)

**Comment by eddelbuettel** [comment]
Please see about [creating a fully reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) including stating what compiler and OS you use.

**Comment by eddelbuettel** [comment]
Closing this as no reproducible example was supplied.

**Comment by eddelbuettel** [comment]
This issue was moved to eddelbuettel/bh#17
