### ISSUE TITLE
 cannot open compressed file 'BH/DESCRIPTION', probable reason 'No such file or directory'

### ISSUE THREAD

**Issue by jrtx** [eddelbuettel/bh#21]
Running this on a Windows 7. Tried to download via CRAN and got the following error:

Installing package into ‘C:/Users/jreid/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/BH_1.58.0-1.zip'
Content type 'application/zip' length 13846694 bytes (13.2 MB)
downloaded 13.1 MB

Warning in install.packages :
  downloaded length 13713408 != reported length 13846694
Warning in install.packages :
  error 1 in extracting from zip file
Warning in install.packages :
  cannot open compressed file 'BH/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

**Comment by eddelbuettel** [comment]
Maybe your filesystem is full, maybe your download got corrupted, maybe you have squirrels in your computer (ok, scratch that) -- but the file is fine:

```
edd@max:/tmp$ wget https://cran.rstudio.com/bin/windows/contrib/3.2/BH_1.58.0-1.zip
--2015-10-20 08:23:08--  https://cran.rstudio.com/bin/windows/contrib/3.2/BH_1.58.0-1.zip
Resolving cran.rstudio.com (cran.rstudio.com)... 54.230.89.34
Connecting to cran.rstudio.com (cran.rstudio.com)|54.230.89.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13846694 (13M) [application/zip]
Saving to: ‘BH_1.58.0-1.zip’

BH_1.58.0-1.zip     100%[=====================>]  13.21M  3.55MB/s   in 3.7s   

2015-10-20 08:23:12 (3.53 MB/s) - ‘BH_1.58.0-1.zip’ saved [13846694/13846694]

edd@max:/tmp$ unzip -l BH_1.58.0-1.zip | grep DESCRIPTION
     1109  2015-08-15 17:42   BH/DESCRIPTION
edd@max:/tmp$ 
```

**Comment by jrtx** [comment]
Found the squirrel... Think R was timing out before that last MB got in there....

thanks.

**Comment by eddelbuettel** [comment]
:+1:

**Comment by eddelbuettel** [comment]
This issue was moved to eddelbuettel/bh#21

**Comment by Maisie27** [comment]
How did you fix this?

**Comment by prncevince** [comment]
@Maisie27 Received same issue, fixed by downloading the source tarball gzip file from https://cran.r-project.org/web/packages/BH/index.html into the current directory and running:
`install.packages('BH_1.66.0-1.tar.gz', repos = NULL)`

**Comment by wahyudinnasrulloh** [comment]
what is squirrel?

**Comment by henningsway** [comment]
a special kind of bug! :)
