### ISSUE TITLE
Boost Flyweight

### ISSUE THREAD

**Issue by jasonelaw** [eddelbuettel/bh#26]
Is it possible to add Boost Flyweight at some point? The memoisation example looks really attractive for a recursive function I'm trying to write using Rcpp.

**Comment by eddelbuettel** [comment]
Sure.  We do have a history of accepting such extensions upon request.  Let me take a look.

**Comment by eddelbuettel** [comment]
That is pretty light:

```r
edd@max:~$ du -h /usr/include/boost/flyweight/
72K     /usr/include/boost/flyweight/detail
212K    /usr/include/boost/flyweight/
edd@max:~$ 
```

though it may depends on some other things we do not yet have but this should not pose a problem.

**Comment by jasonelaw** [comment]
Thanks! You guys really do amazing work with Rcpp. Much appreciated.

**Comment by eddelbuettel** [comment]
Thanks for being so patient. I just got a pull request with Boost ICL (aka interval containers) so I'll add flyweight next.

**Comment by jasonelaw** [comment]
Thank you! Much appreciated.
