### ISSUE TITLE
Add property_tree to get json_parser.hpp?

### ISSUE THREAD

**Issue by aydindemircioglu** [eddelbuettel/bh#29]
sorry, probably i'm just confused, but why is property_tree/json_parser.hpp not part of BH?
is it a non-header-only? or is there any other reason?

(i'm definitely confused as my local update of RcppShark compiles well, but build_win cannot find the above file. )

**Comment by eddelbuettel** [comment]
Look at [this section](https://github.com/eddelbuettel/bh/blob/master/local/scripts/CreateBoost.sh#L96-L129) of the builder script: the _explicitly selected_ Boost libraries and their dependencies are copied.

Boost property_tree is not yet part of this set.

I could look into adding it.

**Comment by aydindemircioglu** [comment]
i realized that in Shark sources json_parser is only used for creating a json file containing the version/build informations. this is not important for Rcppshark, so i removed the dependency.

for me the problem is solved for now, if you want to, you can close the issue.
thanks again for bh and all the other work you do!

**Comment by eddelbuettel** [comment]
I am on the fence. It is probably small relative to the large size we already have, so I may keep this open.

**Comment by eddelbuettel** [comment]
Fixed in 1.62.0-1 which is now master and which should be in CRAN "within days".
