### ISSUE TITLE
FR: Add ScopeExit

### ISSUE THREAD

**Issue by krlmlr** [eddelbuettel/bh#30]
I'm missing `on.exit()` in C++ ;-)

Header-only, available in 1.60.0: http://www.boost.org/doc/libs/1_60_0/libs/scope_exit/doc/html/index.html

**Comment by eddelbuettel** [comment]
Timely.  Was hoping to get to BH 1.62 this weekend.  Will look into this.

**Comment by eddelbuettel** [comment]
Fixed in 1.62.0-1 which is now master and which should be in CRAN "within days".

**Comment by krlmlr** [comment]
Thanks a lot!

**Comment by eddelbuettel** [comment]
That one was 'cheap' -- the Boost library appears to consist of ... a single file `scoped_exit.hpp`.

But the way we do this via `bcp` it is pretty easy either way.  BH is turning a sumo packages.  Almost 10mb for tar.gz ...
