### ISSUE TITLE
Missing files under boost/align?

### ISSUE THREAD

**Issue by yixuan** [eddelbuettel/bh#32]
I noticed that in the `align` folder, some files are missing compared with the official Boost repository, see
[eddelbuettle/bh](https://github.com/eddelbuettel/bh/tree/master/inst/include/boost/align) and [boostorg/align](https://github.com/boostorg/align/tree/develop/include/boost/align).

Is it intentional to reduce package size?

**Comment by eddelbuettel** [comment]
Unintentional side effect from _not officially including_ align.   The files we have were "pulled in":  See how we `bcp` over two sets of packages in [this script](https://github.com/eddelbuettel/bh/blob/master/local/scripts/CreateBoost.sh#L85-L135)

Do you need the align library?

**Comment by yixuan** [comment]
I see. I have a package that is using a library replying on `align`, and that's why I noticed this difference. This package is just for my personal use, and I just need to link to the system boost headers. No worries.

**Comment by eddelbuettel** [comment]
We could keep this open and add it next time ...

**Comment by yixuan** [comment]
Great. I could reopen it when the next release of Boost arrives.

**Comment by eddelbuettel** [comment]
Let's reopen now and leave it here so that neither one of us forgets. :)

**Comment by yixuan** [comment]
Thanks! I almost forgot this issue. 😄

**Comment by eddelbuettel** [comment]
Sorry for the delay.  Other packages kept me busy.   Now waiting on one or two packages to make changes before this goes to CRAN.
