### ISSUE TITLE
Compiling GPU/CUDA R packages linked to BH package fails due to bug in Boost 1.60

### ISSUE THREAD

**Issue by mjmg** [eddelbuettel/bh#33]
Linking against the BH package installed from CRAN for building GPU/CUDA R packages fails with the following error:
/usr/lib64/R/library/BH/include/boost/config/suffix.hpp(510): error: identifier "__float128" is undefined

This is due to a bug in current version of Boost (1.60) used in BH package in CRAN.
https://svn.boost.org/trac/boost/ticket/11852

Can the current version of BH in CRAN based on Boost 1.60 be patched or bumped to the next version?

**Comment by eddelbuettel** [comment]
I am working on it (see the master branch) but it has other issue -- `abort()` gets exposed.  No ETA yet,

**Comment by eddelbuettel** [comment]
BH 1.62.0-1 is now on CRAN.  I assume that fixes your issue.
