### ISSUE TITLE
Please add Boost sort to BH

### ISSUE THREAD

**Issue by artemklevtsov** [eddelbuettel/bh#35]
Hi.
I can't found some boost headers in this package. Please tell me how can I use a missing headers in my package?
Now I install the boost headers in my OS. But I look for a way to do it without external system wide dependencies.

**Comment by eddelbuettel** [comment]
See the DESCRIPTION of the package as well as the README of the repo; they both list a set of included Boost libraries in the BH.

Boost contains more libraries.  We expanded BH over time -- see the NEWS.Rd (or ChangeLog or closed Issue tickets).

So to make it more concrete:  what Boost library are you missing files from?

**Comment by eddelbuettel** [comment]
Is it this [Boost sort library](http://www.boost.org/doc/libs/1_62_0/libs/sort/doc/html/index.html) ?

**Comment by artemklevtsov** [comment]
Yes, it's sort library.

**Comment by eddelbuettel** [comment]
Ok. I'll retitle this ticket and take it as a request to add sort as it seems to be header-only and suitable.

How soon would you need it?  What others have done, eg rstan, is to _augment in their sources_ beyond what we have in BH now, and it to point to it in your sources via an extra `-I...`.  

By the next release (in a few months) it will be included in BH.   Does that work for you?

**Comment by artemklevtsov** [comment]
Sure. For my own use cases I'll use the system wide headers.

**Comment by eddelbuettel** [comment]
If you want to ship to CRAN you could use the 'add missing files to packages sources' route.

**Comment by artemklevtsov** [comment]
Ok. Thank you for the suggestions and quick replies.
My package now is pre alpha. So I'll wait the next `BH` release without any troubles.

**Comment by eddelbuettel** [comment]
All good.  If you have a suggestion for where / how I could say more clearly that BH is a _subset_ of Boost, don't hold back ;-)

**Comment by eddelbuettel** [comment]
This is now in master awaiting a release "real soon now" (but two other issues need to get sorted out first).
