### ISSUE TITLE
Container's pair.hpp triggers runtime error with gcc-UBSAN

### ISSUE THREAD

**Issue by Enchufa2** [eddelbuettel/bh#37]
For instance, [here](https://cran.r-project.org/web/checks/check_results_simmer.html):

```
> library(simmer)
/.../R/test-3.4/BH/include/boost/container/detail/pair.hpp:85:30: runtime error: reference binding to null pointer of type 'const struct piecewise_construct_t'
/.../R/test-3.4/BH/include/boost/container/detail/pair.hpp:85:30: runtime error: reference binding to null pointer of type 'const struct piecewise_construct_t'
/.../R/test-3.4/BH/include/boost/container/detail/pair.hpp:85:30: runtime error: reference binding to null pointer of type 'const struct piecewise_construct_t'
/.../R/test-3.4/BH/include/boost/container/detail/pair.hpp:85:30: runtime error: reference binding to null pointer of type 'const struct piecewise_construct_t'
```

[Solved since v1.63.0](http://www.boost.org/users/history/version_1_63_0.html). It is a very minor issue, because the offending pointer is never used (see ticket [12577](https://svn.boost.org/trac/boost/ticket/12577)), so no hurries at all. I just want to put this on the record, just in case someone struggles with the same issue.

**Comment by eddelbuettel** [comment]
Thank you -- agree completely.  SAN/UBSAN is very useful, and the Boost codebase is so large that a few of these are lurking.  

Referencing it here is the right idea, and we will get it fixed with 1.63, or maybe 1.64.  No real hurry right 
now.

**Comment by Enchufa2** [comment]
Issue fixed in the last update. We can close this. Thanks!

**Comment by eddelbuettel** [comment]
Awesome!  Thanks for the follow-up.
