### ISSUE TITLE
boost/multiprecision/miller_rabin.hpp

### ISSUE THREAD

**Issue by jto888** [eddelbuettel/bh#42]
Hi Dirk,
This is David Silkworth from years back.
I am porting a significant enhancement to my FaultTree package and have run into the following FATAL ERROR.
bdd.cc:23:49: fatal error: boost/multiprecision/miller_rabin.hpp: No such file or directory
I have other issues, like awaiting C++14 enabled compiler in Rtools for Windows, but I would  appreciate if this could be put on the list.  I have confirmed my error goes away if I simply place this header into my local library for BH, but that wouldn't do for package release.

**Comment by eddelbuettel** [comment]
Sure. The way this works (see the BH repo) is that we select particular Boost sub-libraries.  

Maybe multirprecision was not yet part of that mix.  I can add it.  

I have nothing to do with Rtools -- g++ 4.9.3 it is for now.

**Comment by eddelbuettel** [comment]
So I just checked and Boost Multiprecision *is* part of BH since 1.58.0-1 so I am not sure why miller_rabin.hpp is not part of it. I will try to make sure it makes it next time.

**Comment by eddelbuettel** [comment]
It was a typo in the creation script. Should be taken care of in the next upload.

**Comment by eddelbuettel** [comment]
This is now in master awaiting a release "real soon now" (but two other issues need to get sorted out first).
