### ISSUE TITLE
default installation from CRAN not working

### ISSUE THREAD

**Issue by danmsf** [eddelbuettel/bh#44]
Hi, 
Im running R with these settings using Windows7 64 bit through Rstudio Version 1.0.143 :

R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

I tried installing BH - and it failed with the error:  expected download length != download length

[as a side note: For whatever reason after that failure that seems to have messed up my default connection with CRAN so further `install.packages()` returned an error of : missing where expected TRUE or FALSE ... and only after restarting my Windows session did that go away.]

I tried manually downloading the default current version download from CRAN and wasn't able to download it (error...).      { r-release: BH_1.62.0-1.zip}

 In the end I downloaded the older release and that solved my problems.   {r-oldrel: BH_1.62.0-1.zip}

I see they are the same version number so I dont know what the difference is, I can only guess my mirror version of that file is somehow not good...

**Comment by eddelbuettel** [comment]
1) Please see #43
2) Your problems are with _binaries_ provided at CRAN so maybe talk to CRAN

**Comment by danmsf** [comment]
Thanks that was really fast! Yeah I figured that.  And just took a
different version, but I'm guessing you'll get a few more like me until the
binaries are fixed. I'll try and let them know

**Comment by eddelbuettel** [comment]
I just downloaded the r-devel and r-release version from the normal mirror listed first -- and globally distributed hence 'fastest' at https://cloud.r-project.org/web/packages/BH/index.html -- and both are identical (based in `md5sum`) and both list (`unzip -l`) fine.

So I am closing this as it is not an issue with CRAN version,  Maybe the mirror you used was corrupted. maybe your network got in the way.
