### ISSUE TITLE
Error installing from github

### ISSUE THREAD

**Issue by fedeb95** [eddelbuettel/bh#45]
Hi, I was trying to install the library this way:
`library('devtools')
 install_github("eddelbuettel/bh")`
but got the following error:
`Error : /tmp/Rtmp1M5W5j/devtools10b83412e428/eddelbuettel-bh-ea401b9/man/BH-package.Rd: Sections \title, and \name must exist and be unique in Rd files
ERROR: installing Rd objects failed for package ‘BH’
 removing ‘/home/federico/R/x86_64-pc-linux-gnu-library/3.2/BH’
Installation failed: Command failed (1)`
R version 3.2.2, Ubuntu 16.04
I first got the error trying to install sqldf, so decided to try from github

**Comment by eddelbuettel** [comment]
You are doing it wrong.  It is a CRAN package, so please install from CRAN.

**Comment by fedeb95** [comment]
using 
`install.packages('BH')`
 I get the same error:
`Error : /tmp/RtmpxfXx6W/R.INSTALLc0a6c2b91b/BH/man/BH-package.Rd: Sections \title, and \name must exist and be unique in Rd files`

**Comment by eddelbuettel** [comment]
I don't:

```r
R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.


In that flash of darkness he heard people saying - he was a failure - that R was beyond him.
   -- Virginia Woolf
      To The Lighthouse (May 1927)

R> if(identical(getOption('pager'), file.path(R.home('bin'), 'pager'))) # rather take the ESS one
+       options(pager='cat')
R> options(STERM='iESS', str.dendrogram.last="'", editor='emacsclient', show.error.locations=TRUE)
R> install.packages("BH")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/BH_1.62.0-1.tar.gz'
Content type 'application/x-gzip' length 10181096 bytes (9.7 MB)
==================================================
downloaded 9.7 MB

* installing *source* package ‘BH’ ...
** package ‘BH’ successfully unpacked and MD5 sums checked
** inst
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (BH)

The downloaded source packages are in
	‘/tmp/RtmpJ7daej/downloaded_packages’
R> 
```

Note also that 
- your R version is outdated,  R 3.4.1 for Ubuntu is at CRAN
- your log is incomplete

**Comment by fedeb95** [comment]
Upgrading to R 3.2.3 and trying to install again worked. Thank you. From apt-get this is the version of R I get

**Comment by eddelbuettel** [comment]
3.2.3 != 3.4.1 and still outdated _by two years_.  This _will_ limit your ability to install from CRAN.

**Comment by fedeb95** [comment]
I'll try to upgrade R as soon as I can
