### ISSUE TITLE
"Not that", or "Note that"?

### ISSUE THREAD

**Issue by kenahoo** [eddelbuettel/bh#50]
The `README.md` file for this project says "Not that this can be used solely by headers-only Boost libraries. This covers most of Boost, but excludes some libraries which require linking for parts or all of their functionality."

Supposed to be "Note that", I assume?

FWIW, I've decided that whenever I use "note that " in my own writing, I can usually replace it with the empty string. =)

**Comment by eddelbuettel** [comment]
Well spotted, thanks.
