### ISSUE TITLE
Add non-header only Boost libs?

### ISSUE THREAD

**Issue by bob-carpenter** [eddelbuettel/bh#51]
We have a package ([rstan](https://cran.r-project.org/web/packages/rstan/index.html) package) that currently uses BH for Boost, but is soon going to need MPI for parallelization.  

Boost's MPI libraries are not header only---they require the Boost build tools and then linking.

Is there any chance these could be added to BH or should we just go ahead and add the relevant libs ourselves in the [stan headers package](https://cran.r-project.org/web/packages/StanHeaders/index.html) package?

**Comment by eddelbuettel** [comment]
BH has always aimed for being header-only, so (file)system, regex, ... and other niceties.  

I happen to like MPI.  I would be nice to have better support, but I fear a ginormous can of worms across all three (core) platforms given that CRAN apparently cannot even sort OpenMP on macOS out reliably.

**Comment by eddelbuettel** [comment]
See the README.md which states clearly

> Note that this can be used solely by headers-only Boost libraries. This covers most of Boost, but excludes some libraries which require linking for parts or all of their functionality.

**Comment by eddelbuettel** [comment]
But if there are other _header-only_ components BH could / should have we're always open for business.  Just the linking part is off-limits by choice.

**Comment by bob-carpenter** [comment]
Thanks for the instant response.  We're targeting command-line and linux first, as I suspect you're right about the can of worms.  I think everything we need that's not in BH is not header only, so we'll just roll it into our own code when we get around to integrating with R.
