### ISSUE TITLE
class std::auto_ptr' is deprecated 

### ISSUE THREAD

**Issue by jeroen** [eddelbuettel/bh#57]
When compiling with gcc-8 (currently being deployed on CRAN's Fedora machines) many packages that include BH see this warning: 

```
warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
``` 

It looks like CRAN will [start flagging](https://github.com/wch/r-source/commit/2a9ae281fe790dfee6c8e0d3136d23440bbae145) these warnings in CMD check, so they will have to be fixed.

Some packages that have this include anytime, dplyr, later, svglite, purrrlyr, highlight, ldat, readr, and a [bunch more](https://github.com/r-windows/checks/search?utf8=%E2%9C%93&q=auto_ptr&type=).

**Comment by eddelbuettel** [comment]
We also get this with `g++-7` ie I see it on my Ubuntu boxen too.

I recommend setting something in `~/.R/Makevars` to silence this. The laptop I type this on currently has

```make
#PEDANTIC=-pedantic -Werror
PEDANTIC=-Wno-deprecated-declarations

## for C code
CFLAGS=               -g -O3 -Wall -pipe $(PEDANTIC) -Wno-unused -std=gnu99 -march=native
#CFLAGS=               -O3 -g0 -Wall -pipe $(PEDANTIC) -std=gnu99 -I/usr/local/cuda/include

## for C++ and C++11 code
#CXXFLAGS=            	-g -O3 -Wall -pipe -Wno-unused $(PEDANTIC) -DRCPP_NEW_DATE_DATETIME_VECTORS
#CXX1XFLAGS=		-g -O3 -Wall -pipe -Wno-unused $(PEDANTIC) -DRCPP_NEW_DATE_DATETIME_VECTORS
CXXFLAGS=            	-g -O3 -Wall -pipe -Wno-unused $(PEDANTIC) -march=native
CXX1XFLAGS=		-g -O3 -Wall -pipe -Wno-unused $(PEDANTIC) -march=native
CXX11FLAGS=		-g -O3 -Wall -pipe -Wno-unused $(PEDANTIC) -march=native
CXX14FLAGS=		-g -O3 -Wall -pipe -Wno-unused $(PEDANTIC) -march=native
```

and that works perfectly well.   I am fairly sure I do not want to edit Boost fikes for CRAN's pleasure so this will just remain open.

**Comment by eddelbuettel** [comment]
Add `-DBOOST_NO_AUTO_PTR` to the compiler flags, or your source file, and all is silent.
