### ISSUE TITLE
BH is taking too much time (More than 30 mins) to install even after successful download.

### ISSUE THREAD

**Issue by goodwilrv** [eddelbuettel/bh#61]
I am trying to install BH, but it is taking too much time to install even after successful donwload.
I saw the below message,

-----------------------------------------
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/BH_1.69.0-1.zip'
Content type 'application/zip' length 19008275 bytes (18.1 MB)
downloaded 18.1 MB
---------------------------------------------
But after that it has been trying to install it for a very very long time. :-(. Is there a way to speed up ?

**Comment by eddelbuettel** [comment]
Use a better file system / disks / OS:

```r
R> system.time(install.packages("BH"))
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/BH_1.69.0-1.tar.gz'
Content type 'application/x-gzip' length 12378154 bytes (11.8 MB)
==================================================
downloaded 11.8 MB

* installing *source* package ‘BH’ ...
** package ‘BH’ successfully unpacked and MD5 sums checked
** using staged installation
** inst
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (BH)

The downloaded source packages are in
        ‘/tmp/RtmpYmaz2f/downloaded_packages’
   user  system elapsed 
  7.915   2.523  10.496 
R> 
```

10.5 seconds elapsed _including the download_ for me.  Linux, 1 1/2 year old "nice" machine, but nothing extravagant.

**Comment by goodwilrv** [comment]
I am using a very high performance PC, with pretty good RAM, with Windws 10. Tried again by reinstalling R inside D:// as well as C://Programs directory. R version: 3.6.0. But it doesn't succeed even after successful download. 

> system.time(install.packages("BH"))
Installing package into ‘\\S575FJIYH061.jpadc.corpintra.net/home/GAUTKUM/Data/My Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://mirror-hk.koddos.net/CRAN/bin/windows/contrib/3.6/BH_1.69.0-1.zip'
Content type 'application/zip' length 19008275 bytes (18.1 MB)
downloaded 18.1 MB

and it never finishes the installation.

May be this issue is because somehow it is trying to access network resource \\S575FJIYH061.jpadc.corpintra.net/ to refer to a folder locally ? Is there a way for me to specify the path in terms of local address, like "C:\Users\GAUTKUM\Data\My Documents/R/win-library/3.6" etc ??

I also see the BH zipped folder downloaded nicely at the below location,
C:\Users\GAUTKUM\AppData\Local\Temp\RtmpU9MWZS\downloaded_packages.
Is there a way to do the installation manually using this downloaded folder becuase installation.packages command fails ?

**Comment by markvanderloo** [comment]
I have some experience with MS networked file systems and at least where I work that is really really slow. So blame the infra guys or MS. On the positive side,  `?install.packages` tells us that you can install in any folder you want:
```r
install.packages("BH", lib="path/to/your/local/folder/that/is/not/on/the/network")
```
If all your folders are virtualized, that will not help. 

Alternatively, just download the `.zip` straight from CRAN and unpack in your library directory to install.

**Comment by goodwilrv** [comment]
Many thanks. I finally had to unzip it manually from the downloaded zipped folder and it worked fine. Many thanks for replying so quickly. 

Regards
Gautam Kumar

**Comment by eddelbuettel** [comment]
Your network drive is the guilty party (or, more specifically, how Windows deals with it).  The workaround you used is fine.  

You can of course also install from source. In BH's case that is easy as it is essentially just a massive copy.

**Comment by NanisTe** [comment]
I install it on Windows 10 C drive no virtual or network drives involved but still it takes more than 10 minutes to install BH package using Rstudio!
