### ISSUE TITLE
Backporting deprecation warning fix for integer_log2.hpp ?

### ISSUE THREAD

**Issue by octomike** [eddelbuettel/bh#64]
Hi!

I realize you are reluctant to modify boost source / backporting things for stability reasons, but I still wonder if it's possible to backport [this single line fix](https://github.com/boostorg/random/commit/1be44d405e48a42a63bd8d2dae739560b486a55c) to silence compile warnings like this:

```
In file included from /usr/lib/R/site-library/BH/include/boost/random/detail/integer_log2.hpp:19:0,
                 from /usr/lib/R/site-library/BH/include/boost/random/detail/large_arithmetic.hpp:19,
                 from /usr/lib/R/site-library/BH/include/boost/random/detail/const_mod.hpp:23,
                 from /usr/lib/R/site-library/BH/include/boost/random/linear_congruential.hpp:30,
                 from /usr/lib/R/site-library/BH/include/boost/random/additive_combine.hpp:27,
                 from /usr/lib/R/site-library/rstan/include/rstan/stan_fit.hpp:15,
                 from /usr/lib/R/site-library/rstan/include/rstan/rstaninc.hpp:3,
                 from stan_files/ctsmgen.hpp:18,
                 from stan_files/ctsmgen.cc:3:
/usr/lib/R/site-library/BH/include/boost/pending/integer_log2.hpp:7:89: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
```

**Comment by eddelbuettel** [comment]
It should get taken care of when I move to Boost 1.71 (or maybe 1.72 will just be out by then).

**Comment by octomike** [comment]
Alright :+1:

**Comment by eddelbuettel** [comment]
I am with you though that it is annoying, as is CRAN's insistence to now allow compiler warning suppression (but yes, there is of course a defensible reason behind it) yet .... the line noise is a pain.

**Comment by octomike** [comment]
I completely understand, just wanted to double check your take on this :)
