### ISSUE TITLE
Package missing from org.renjin.cran repositories

### ISSUE THREAD

**Issue by charneykaye-gw** [eddelbuettel/bh#70]
I also posted an issue on https://stackoverflow.com/questions/59572516/org-renjin-cran-libraries-missing-from-repositories inquiring if anyone has run into this from the org.renjin.cran standpoint.

It seems that these dependencies were removed from repositories. Note following the above error that https://repository.mulesoft.org/nexus/content/repositories/public/org/renjin/cran/ no longer contains a BH folder, and https://nexus.bedatadriven.com/content/groups/public/org/renjin/cran/BH/ contains only signatures of files, but no actual library .pom files.

This is weird because http://packages.renjin.org/package/org.renjin.cran/BH/1.69.0-1 specifically claims that those packages exist.

I have been unable to find any information about planned changes to this.

**Comment by eddelbuettel** [comment]
I am not sure how you think I can help you.  I maintain BH.  It is in this repo.  It is at CRAN.

I have nothing to do with renjin -- that is all @akbertram et al. Can you maybe sort it out with them?

**Comment by akbertram** [comment]
It does look something is wrong with the repository. I'll try to take a look today.

**Comment by akbertram** [comment]
There was indeed a configuration problem, which has now been resolved. The build for BH 1.69.0 should again be available from nexus.bedatadriven.com.

**Comment by eddelbuettel** [comment]
Sweet! Thanks for fixing it!  I did upload 1.72.0 recently, made on small mistake so that we are at 1.72.0-2 and will follow up (once CRAN reopens) with 1.72.0-3 (which for now is on the ghrr drat as well as per a recent tweet).   Maybe you can get to that too?

**Comment by charneykaye-gw** [comment]
Thanks so much for raising this issue to the appropriate party's attention, that's the best case I was hoping for.

**Comment by eddelbuettel** [comment]
Sounds good.  Will close this now given that @akbertram took over and is on it.
