### ISSUE TITLE
QVM support

### ISSUE THREAD

**Issue by gitboosting** [eddelbuettel/bh#97]
I am wondering if there's a plan to support qvm: https://www.boost.org/doc/libs/1_80_0/libs/qvm/doc/html/index.html

I analyze data from sensors (e.g. accelerometers, gyroscopes, ...) in inertial measurement units and could benefit greatly with algorithms in quaternions, vectors and matrices.

**Comment by eddelbuettel** [comment]
Yes, could do -- see old issue tickets for other requests we honoured in the past.

Can you confirm that it is header-only and does not require linking?

**Comment by gitboosting** [comment]
Thanks for your kind response. 

It says on qvm's repo (https://github.com/boostorg/qvm) that it is header-only. But please let me know if there are ways to confirm it besides taking what it says on face value. Thanks again.

QVM is included in official [Boost](https://www.boost.org/) releases.
For maximum portability, the library is also available in single-header format, in two variants (direct download links):
- [qvm.hpp](https://boostorg.github.io/qvm/qvm.hpp): single header containing the complete QVM source, including the complete set of swizzling overloads.
- [qvm_lite.hpp](https://boostorg.github.io/qvm/qvm_lite.hpp): single header containing everything except for the swizzling overloads.

**Comment by eddelbuettel** [comment]
Yes, that's what I saw too (and I had never seen a possible libboost_qvm library either) but as you appear to be a user I thought I might as well as you :)    And yes, language of 'single header' confirms that too.

**Comment by eddelbuettel** [comment]
This will be in BH 1.84.0 which I am preparing.  There are very minor repurcussions with five packages so this will be on CRAN in January.  Until then you can get it from here, or from [the r-universe builds](https://eddelbuettel.r-universe.dev/BH) and I may add it to the [ghrr drat](https://ghrr.github.io/drat/) as well.

**Comment by gitboosting** [comment]
@eddelbuettel This is wonderful. Thank you. Happy New Year.

**Comment by eddelbuettel** [comment]
Just waiting for CRAN to reopen...

**Comment by eddelbuettel** [comment]
BH 1.84.0-0 is now at CRAN, with QVM.  Thanks for the suggestion, and your patience!
